mod commands;
mod config;
mod log_layer;
mod status;
mod worker;

use std::collections::VecDeque;
use std::sync::{Arc, Mutex};

#[cfg(target_os = "macos")]
use tauri::LogicalPosition;
use tauri::{Manager, WebviewUrl, WebviewWindowBuilder, WindowEvent};
use tauri_specta::{collect_commands, collect_events, Builder, Event};
use tokio::sync::watch;
use tracing_subscriber::prelude::*;

use config::{load_config, DesktopConfig};
use log_layer::{FrontendLogEntry, TauriLogLayer};
use status::{AppStatus, SyncErrorPayload};
use worker::BgCmd;

// ── Bindings export (test-only utility) ───────────────────────────────────────

#[cfg(test)]
mod tests {
    use tauri_specta::{collect_commands, collect_events, Builder};

    use super::*;

    /// Run with `cargo test -p git-sync-tauri export_bindings` to regenerate
    /// `src/bindings.ts` without needing to start the full Tauri app.
    #[test]
    fn export_bindings() {
        let builder = Builder::<tauri::Wry>::new()
            .commands(collect_commands![
                commands::get_config,
                commands::get_status,
                commands::set_config,
                commands::sync_now,
                commands::validate_repo_path,
                commands::pick_folder,
                commands::get_log_history,
            ])
            .events(collect_events![StatusUpdateEvent, LogEntryEvent]);

        builder
            .export(
                specta_typescript::Typescript::default().header(
                    "// This file is auto-generated by tauri-specta. Do not edit manually.\n",
                ),
                concat!(env!("CARGO_MANIFEST_DIR"), "/../src/bindings.ts"),
            )
            .expect("Failed to export TypeScript bindings");
    }
}

// ── Typed events ──────────────────────────────────────────────────────────────

#[derive(Clone, serde::Serialize, specta::Type, tauri_specta::Event)]
#[serde(transparent)]
pub struct StatusUpdateEvent(pub AppStatus);

#[derive(Clone, serde::Serialize, specta::Type, tauri_specta::Event)]
#[serde(transparent)]
pub struct LogEntryEvent(pub FrontendLogEntry);

// ── App state ─────────────────────────────────────────────────────────────────

pub struct AppState {
    pub config: DesktopConfig,
    pub worker_tx: tokio::sync::mpsc::UnboundedSender<BgCmd>,
}

pub struct StatusState(watch::Receiver<AppStatus>);

pub struct LogState {
    pub history: Arc<Mutex<VecDeque<FrontendLogEntry>>>,
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let (log_tx, mut log_rx) = tokio::sync::mpsc::unbounded_channel::<FrontendLogEntry>();
    let log_history = Arc::new(Mutex::new(VecDeque::<FrontendLogEntry>::new()));
    let log_history_for_task = Arc::clone(&log_history);

    tracing_subscriber::registry()
        .with(
            tracing_subscriber::fmt::layer()
                .with_filter(tracing_subscriber::EnvFilter::from_default_env()),
        )
        .with(TauriLogLayer::new(log_tx))
        .init();

    let config = load_config();
    let (status_tx, status_rx) = watch::channel(AppStatus::default());
    let status_tx = Arc::new(status_tx);
    let (cmd_tx, cmd_rx) = tokio::sync::mpsc::unbounded_channel::<BgCmd>();

    {
        let status_bg = Arc::clone(&status_tx);
        let init_cfg = config.clone();
        std::thread::spawn(move || worker::run_background(init_cfg, status_bg, cmd_rx));
    }

    let status_rx_forwarder = status_rx.clone();

    // ── tauri-specta builder ──────────────────────────────────────────────────

    let builder = Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::get_config,
            commands::get_status,
            commands::set_config,
            commands::sync_now,
            commands::validate_repo_path,
            commands::pick_folder,
            commands::get_log_history,
        ])
        .events(collect_events![StatusUpdateEvent, LogEntryEvent]);

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default()
                .header("// This file is auto-generated by tauri-specta. Do not edit manually.\n"),
            "../src/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");

    let invoke_handler = builder.invoke_handler();

    tauri::Builder::default()
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_os::init())
        .plugin(tauri_plugin_dialog::init())
        .manage(Mutex::new(AppState {
            config,
            worker_tx: cmd_tx,
        }))
        .manage(Mutex::new(StatusState(status_rx)))
        .manage(LogState {
            history: log_history,
        })
        .setup(move |app| {
            builder.mount_events(app);

            // Build main window with platform-specific title bar style.
            let win_builder = WebviewWindowBuilder::new(app, "main", WebviewUrl::default())
                .title("Git Sync")
                .inner_size(680.0, 520.0)
                .min_inner_size(520.0, 440.0)
                .shadow(true);

            #[cfg(target_os = "macos")]
            let win_builder = win_builder
                .title_bar_style(tauri::TitleBarStyle::Overlay)
                .traffic_light_position(LogicalPosition::new(13, 18))
                .hidden_title(true);

            #[cfg(not(target_os = "macos"))]
            let win_builder = win_builder.decorations(false);

            win_builder.build()?;

            // Push status updates to the frontend and send desktop notifications
            // whenever a repository transitions into an error or conflict state.
            let app_handle = app.handle().clone();
            let mut rx = status_rx_forwarder;
            tauri::async_runtime::spawn(async move {
                let mut prev_error_keys: Vec<Option<String>> =
                    vec![None; rx.borrow().repos.len()];
                loop {
                    if rx.changed().await.is_err() {
                        break;
                    }
                    let snapshot = rx.borrow_and_update().clone();

                    // Reset tracking when the repo count changes (e.g. after reconfigure).
                    if prev_error_keys.len() != snapshot.repos.len() {
                        prev_error_keys = vec![None; snapshot.repos.len()];
                    }

                    for (i, repo) in snapshot.repos.iter().enumerate() {
                        let key = error_key(&repo.error);
                        if key.is_some() && key.as_deref() != prev_error_keys[i].as_deref() {
                            if let Some(ref err) = repo.error {
                                let (title, body) = notification_text(&repo.repo_path, err);
                                use tauri_plugin_notification::NotificationExt;
                                app_handle
                                    .notification()
                                    .builder()
                                    .title(&title)
                                    .body(&body)
                                    .show()
                                    .ok();
                            }
                        }
                        prev_error_keys[i] = key;
                    }

                    StatusUpdateEvent(snapshot).emit(&app_handle).ok();
                }
            });

            // Forward log entries to the frontend and accumulate history.
            let app_handle2 = app.handle().clone();
            tauri::async_runtime::spawn(async move {
                loop {
                    match log_rx.recv().await {
                        Some(entry) => {
                            {
                                let mut hist = log_history_for_task.lock().unwrap();
                                hist.push_back(entry.clone());
                                if hist.len() > 1000 {
                                    hist.pop_front();
                                }
                            }
                            LogEntryEvent(entry).emit(&app_handle2).ok();
                        }
                        None => break,
                    }
                }
            });

            // System tray
            use tauri::{
                menu::{Menu, MenuItem},
                tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent},
            };

            let quit_item = MenuItem::with_id(app, "quit", "Quit Git Sync", true, None::<&str>)?;
            let menu = Menu::with_items(app, &[&quit_item])?;

            TrayIconBuilder::new()
                .icon(app.default_window_icon().unwrap().clone())
                .menu(&menu)
                .show_menu_on_left_click(false)
                .on_tray_icon_event(|tray, event| {
                    if let TrayIconEvent::Click {
                        button: MouseButton::Left,
                        button_state: MouseButtonState::Up,
                        ..
                    } = event
                    {
                        let app = tray.app_handle();
                        if let Some(window) = app.get_webview_window("main") {
                            if window.is_visible().unwrap_or(false) {
                                window.hide().unwrap();
                            } else {
                                window.show().unwrap();
                                window.set_focus().unwrap();
                            }
                        }
                    }
                })
                .on_menu_event(|app, event| {
                    if event.id() == "quit" {
                        app.exit(0);
                    }
                })
                .build(app)?;

            Ok(())
        })
        .on_window_event(|window, event| {
            if let WindowEvent::CloseRequested { api, .. } = event {
                window.hide().unwrap();
                api.prevent_close();
            }
        })
        .invoke_handler(invoke_handler)
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

/// Returns a short string key identifying the current error category, used to
/// detect transitions into a new error state so we don't re-notify on every tick.
fn error_key(error: &Option<SyncErrorPayload>) -> Option<String> {
    error.as_ref().map(|e| match e {
        SyncErrorPayload::Auth { .. } => "auth".to_string(),
        SyncErrorPayload::Network { .. } => "network".to_string(),
        SyncErrorPayload::Conflict { .. } => "conflict".to_string(),
        SyncErrorPayload::ConflictBranch { .. } => "conflict_branch".to_string(),
        SyncErrorPayload::Config { .. } => "config".to_string(),
        SyncErrorPayload::State { .. } => "state".to_string(),
        SyncErrorPayload::Unknown { .. } => "unknown".to_string(),
    })
}

/// Builds the notification title and body for a repository error.
fn notification_text(repo_path: &str, error: &SyncErrorPayload) -> (String, String) {
    let repo_name = std::path::Path::new(repo_path)
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("Unknown repository")
        .to_string();

    match error {
        SyncErrorPayload::Conflict { message } => (
            format!("{}: Merge conflict", repo_name),
            message.clone(),
        ),
        SyncErrorPayload::ConflictBranch { branch, message } => (
            format!("{}: Conflicts saved to branch", repo_name),
            format!("{} — {}", branch, message),
        ),
        SyncErrorPayload::Auth { message } => (
            format!("{}: Authentication failed", repo_name),
            message.clone(),
        ),
        SyncErrorPayload::Network { message } => (
            format!("{}: Network error", repo_name),
            message.clone(),
        ),
        SyncErrorPayload::Config { message } => (
            format!("{}: Configuration error", repo_name),
            message.clone(),
        ),
        SyncErrorPayload::State { message } => (
            format!("{}: Repository needs attention", repo_name),
            message.clone(),
        ),
        SyncErrorPayload::Unknown { message } => (
            format!("{}: Sync error", repo_name),
            message.clone(),
        ),
    }
}
